#!/usr/bin/env bash

source $(dirname $0)/signalresource
set -eu
code=0

echo "# handle" 

got=$(handle "")
expected="signal-resource successful"
if [ "$got" = "$expected" ]; then
    echo "ok - [handle] successful signal-resource"
else
    echo "not ok - [handle] successful signal-resource"
    echo ""
    echo "  expected: ${expected}"
    echo "  got: ${got}"
    echo ""
    code=1
fi

got=$(handle)
expected="signal-resource successful"
if [ "$got" = "$expected" ]; then
    echo "ok - [handle] successful signal-resource"
else
    echo "not ok - [handle] successful signal-resource"
    echo ""
    echo "  expected: ${expected}"
    echo "  got: ${got}"
    echo ""
    code=1
fi

got=$(handle "ValidationError")
expected="disregarding ValidationError from signal-resource"
if [ "$got" = "$expected" ]; then
    echo "ok - [handle] disregard ValidationError"
else
    echo "not ok - [handle] disregard ValidationError"
    echo ""
    echo "  expected: ${expected}"
    echo "  got: ${got}"
    echo ""
    code=1
fi

got=$(handle "error")
expected="received error from signal-resource, retrying after 30 second pause..."
if [ "$got" = "$expected" ]; then
    echo "ok - [handle] disregard ValidationError"
else
    echo "not ok - [handle] disregard ValidationError"
    echo ""
    echo "  expected: ${expected}"
    echo "  got: ${got}"
    echo ""
    code=1
fi

echo "# run" 

function aws() {
    exit 0
}

STACK_NAME=xxx
INSTANCE_ID=xxx
got=$(run)
expected="signal-resource successful"
if [ "$got" = "$expected" ]; then
    echo "ok - [run] successful signal-resource"
else
    echo "not ok - [run] successful signal-resource"
    echo ""
    echo "  expected: ${expected}"
    echo "  got: ${got}"
    echo ""
    code=1
fi

function aws() {
    >&2 echo "this is a ValidationError"
}

STACK_NAME=xxx
INSTANCE_ID=xxx
got=$(run) 
expected="disregarding this is a ValidationError from signal-resource"
if [ "$got" = "$expected" ]; then
    echo "ok - [run] disregard ValidationError"
else
    echo "not ok - [run] disregard ValidationError"
    echo ""
    echo "  expected: ${expected}"
    echo "  got: ${got}"
    echo ""
    code=1
fi

function aws() {
    >&2 echo "error"
}

STACK_NAME=xxx
INSTANCE_ID=xxx
expected="received error from signal-resource, retrying after 30 second pause...
received error from signal-resource, retrying after 30 second pause...
received error from signal-resource, retrying after 30 second pause...
received error from signal-resource, retrying after 30 second pause...
received error from signal-resource, retrying after 30 second pause...
received error from signal-resource, retrying after 30 second pause...
... stopping signal retry after 180 seconds"
if got=$(run 1); then
    echo "not ok - [run] retries other errors"
    echo ""
    echo "  expected: $(runRetries)"
    echo "  got: ${got}"
    echo ""
    code=1
else
    echo "ok - [run] retries other errors"
fi

if [ $code == 1 ]; then
    echo ""
    echo "not ok - tests fail"
    exit 1
else
    echo ""
    echo "ok - tests pass"
    exit 0
fi
